### ISSUE TITLE
Plans to update to rsocket-java 0.9.11?

### ISSUE THREAD

**Issue by yschimke** [mostroverkhov/firebase-rsocket-server#10]
Just wanted to understand if you ever plan to update to a recent release of rsocket-java.  If so have you considered using the URI support instead of defining your own transport classes?

https://github.com/rsocket/rsocket-cli/search?utf8=%E2%9C%93&q=UriTransportRegistry&type=
https://github.com/rsocket/rsocket-java/blob/1.0.x/rsocket-core/src/main/java/io/rsocket/uri/UriTransportRegistry.java

**Comment by yschimke** [comment]
BTW I wrote a simple Android O demo client and server. If this is useful it could be interesting to have a different endpoint that shows reactive data from firebase.

http://rsocket-demo.herokuapp.com/

https://github.com/rsocket/rsocket-demo-android-java8
https://github.com/rsocket/rsocket-demo

**Comment by mostroverkhov** [comment]
Hello, yes update will definetely happen, not sure any time soon ( think of months).  Originally, when this code was factored out for public access, rsocket-java depended on rxjava2. Then rsocket switched to reactor, and given my underlying library talking to firebase was based on rxjava1, i stayed with older version just to avoid 3 reactive libs in such small project. Eventually, i will rewrite this with reactor.

**Comment by mostroverkhov** [comment]
Android O should be able to run client part of firebase-rsocket-server, so only work needed is firebase project with free plan, deployment of firebase-rsocket-server, and external server which will act as native firebase client for writing sample data. Once I finish with leasing support, I can come up with investigation and PR as this probably will not take much effort.

**Comment by yschimke** [comment]
Yep, if it helps to cohost anything in the permanent heroku instance I have for rsocket-demo, let me know.

No rush, I was just curious, looks like the kind of thing I was thinking of building :)
